### ISSUE TITLE
Disabling editor removes links for "Publish"/"Preview"

### ISSUE THREAD

**Issue by dajare** [franciscoarocas/flatpress-responsive-admin-theme#2]
If you choose the option to disable the editor, then the buttons for saving the post disappear. Here is the "HTML" option enabled:

<img width="936" alt="__0-fp01" src="https://user-images.githubusercontent.com/40625/71555527-5798a700-2a25-11ea-8e0a-0f61c9492168.png">

And here is the same (static) page with the "Disable Editor" option selected:

<img width="1007" alt="__0-fp02" src="https://user-images.githubusercontent.com/40625/71555539-75fea280-2a25-11ea-9e90-05cf772ae0aa.png">

The same is true of the options panel ("Publish"/"Save"/"Preview") when editing Entries. The "Disable Editor" option still needs some mechanism to save the post/edit! ;) Unless I misunderstand what "disabling" is intended to achieve....

**Comment by franciscoarocas** [comment]
Fixed
